#!/bin/bash
#SBATCH --job-name=crack_simul
#SBATCH --ntasks=256
#SBATCH --partition=fat
#SBATCH --cpus-per-task=1
#SBATCH --time=20:00:00
#SBATCH --error=slurm-%j.stderr
#SBATCH --output=slurm-%j.stdout
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lei.zhang@rug.nl

# Load the modules
module load 2021
module restore set-gap

# set the correct path for lammps executable
mpirun -np 256 lmp_mpi -in crack.in