#!/bin/bash
#SBATCH --job-name=train_gap_turbo
#SBATCH --partition=thin
#SBATCH --nodes=1   # number of nodes
#SBATCH --time=2:00:00
#SBATCH --exclusive
#SBATCH --error=slurm-%j.stderr
#SBATCH --output=slurm-%j.stdout
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lei.zhang@rug.nl

# lei.zhang, 12 Dec 2021, lei.zhang@rug.nl

module restore set-gap

# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

echo $SLURM_CPUS_ON_NODE

/home/marescaf/software/QUIP_OPENMP/build/linux_x86_64_gfortran_openmp/gap_fit at_file=train.xyz \
gap={ distance_Nb order=2 cutoff=5.0 n_sparse=25 covariance_type=ard_se  \
delta=1.0 theta_uniform=2.5 sparse_method=uniform compact_clusters=True \
:soap_turbo l_max=8 alpha_max={{8}} \
atom_sigma_r={{0.25}} atom_sigma_t={{0.25}} \
atom_sigma_r_scaling={{ 0.0}} atom_sigma_t_scaling={{0.0}} \
zeta=4 rcut_hard=3.0 rcut_soft=2.5 \
delta=1.0 basis="poly3" \
scaling_mode="polynomial"  amplitude_scaling={{1.0}}  \
n_species=1 species_Z={26} add_species=F \
compress_mode="trivial" \
radial_enhancement=1 central_weight={{1.0}}  covariance_type=dot_product \
config_type_n_sparse={slice_sample_high:250:phonons_54_high:250:phonons_128_high:250:prim_random:100:default:1500} \
sparse_method=cur_points \
:soap_turbo l_max=8 alpha_max={{8}} \
atom_sigma_r={{0.5}} atom_sigma_t={{0.5}} \
atom_sigma_r_scaling={{ 0.0}} atom_sigma_t_scaling={{0.0}} \
zeta=4 rcut_hard=5.0 rcut_soft=4.0 \
delta=1.0 basis="poly3" \
scaling_mode="polynomial"  amplitude_scaling={{1.0}}  \
n_species=1 species_Z={26} add_species=F compress_mode="trivial" \
radial_enhancement=1 central_weight={{1.0}}  covariance_type=dot_product \
config_type_n_sparse={slice_sample_high:250:phonons_54_high:250:phonons_128_high:250:prim_random:100:default:1500} \
sparse_method=cur_points} \
sparse_jitter=1e-12 \
default_sigma={0.005 0.2 1.0 0.0}  \
config_type_sigma={slice_sample_high:0.0001:0.01:0.01:0.0:phonons_54_high:0.001:0.05:1.0:0.0:phonons_128_high:0.001:0.05:1.0:0.0:prim_random:0.0001:0.01:0.01:0.0} \
energy_parameter_name=energy force_parameter_name=force virial_parameter_name=virial  \
do_copy_at_file=F  \
sparse_separate_file=T  \
gp_file=gap_Fe_test.xml \
openmp_chunk_size=1000 \
e0={Fe:-3455.6995339}  
