#!/bin/bash
#SBATCH --job-name=c_110
#SBATCH --ntasks=128
#SBATCH --partition=thin
#SBATCH --cpus-per-task=1
#SBATCH --time=2:00:00
#SBATCH --error=slurm-%j.stderr
#SBATCH --output=slurm-%j.stdout
#SBATCH --mail-type=ALL
#SBATCH --mail-user=lei.zhang@rug.nl

# Load the modules
module load 2021
module restore set-gap

# set the correct path for lammps executable
mpirun -np 128 lmp_mpi -in crack.in
